version: '3.6'

services:

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest

  todolist-api:
    image: todolist-api:dev
    build:
      context: .
      dockerfile: ToDoList.API/Dockerfile
    depends_on:
      - sqldata
    command: sh -c 'dockerize -wait tcp://sqldata:1433 -timeout 20s -wait-retry-interval 2s -- dotnet ToDoList.API.dll'